version: "3.3"
services:
  user_app4:
    image: user_app4:lastest
    build:
      context: ./frontend/user_app4
      dockerfile: Dockerfile
    links:
      - analytics_app
    ports:
      - "3896:80"
    networks:
      - private
      - public
  analytics_app:
    image: analytics_app:lastest
    build:
      context: ./frontend/analytics_app
      dockerfile: Dockerfile
    restart: always
    ports:
     - "3893:5000"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - private
  celery:
    image: celery
    build:
      context: ./frontend/analytics_app
      dockerfile: Dockerfile_celery
    links:
      - redis
    depends_on:
      - analytics_app
      - redis
    networks:
      - private
  redis:
      image: "redis:alpine"
      command: --port 3894
      ports:
        - "3894:3894"
      networks:
        - private
  analytics_db:
    image: analytics_db:latest
    build: 
      context: ./frontend/analytics_app
      dockerfile: Dockerfile_db
    env_file:
      - ./frontend/analytics_app/postgres.env
    ports:
      - '3895:3895'
    command: -p 3895
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - private
  backend:
    image: backend:lastest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3785:3785"
    networks:
      - private
      - public
volumes:
  db-data:

networks:
  public:
  private:
    internal: true
