CREATE TABLE actions (
    id SERIAL PRIMARY KEY,
    userid VARCHAR NOT NULL,
    page VARCHAR NOT NULL,
    version INT NOT NULL,
    tstamp TIMESTAMP NOT NULL,
    actions JSONB NOT NULL
);

CREATE TABLE top10 (
  ID SERIAL PRIMARY KEY,
  userid VARCHAR NOT NULL,
  version INT NOT NULL,
  poseWeight DECIMAL NOT NULL,
  colorWeight DECIMAL NOT NULL,
  objectWeight DECIMAL NOT NULL,
  topX JSON NOT NULL,
  PAK DECIMAL NOT NULL,
  SRC DECIMAL NOT NULL,
  MSE DECIMAL NOT NULL,
  duration INT NOT NULL
);
